# This is a basic workflow to help you get started with Actions

name: Firebase Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the release/production branch
  push:
    branches: [ release/production ]
  pull_request:
    branches: [ release/production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Installs Firebase
      - name: Install Firebase
        run: npm install -g firebase-tools
        
      - name: Access Firebase
        run: firebase use juler-sites --token $FIREBASE_TOKEN

      # Runs a single command using the runners shell
      - name: Deploy to Firebase
        run: firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --only hosting:techvault --non-interactive --token $FIREBASE_TOKEN
