# This is a basic workflow to help you get started with Actions

name: Firebase Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the release/production branch
  push:
    branches: [ release/production ]
  pull_request:
    branches: [ release/production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      # Creates directory
      - name: Create techvault dir
        run: |
          mkdir techvault
          shopt -s extglob
          mv !(techvault) techvault
    
      # Clones Firebase Deploy Info
      - name: Clone Juler-Hosting
        uses: actions/checkout@master
        with:
          repository: Juler-Sites/juler-hosting
          path: .
          
      # Get to Host Dir
      - name: Move to Host
        run: |
          ls -al
      
      # Installs Firebase
      - name: Install Firebase
        run: npm install -g firebase-tools
        
      # Access Firebase
      - name: Access Firebase
        run: |
          firebase use juler-sites --token ${{ secrets.FIREBASE_TOKEN }}

      # Deploys Firebase
      - name: Deploy to Firebase
        run: firebase deploy --only hosting:techvault --non-interactive --token ${{ secrets.FIREBASE_TOKEN }}
